site:
  title: "Markrealm Documentation"
  baseUrl: "/"

sidebar:
  order:
    - "index.md"
    - "getting-started.md"
    - "api-reference.md"

linkcheck:
  enabled: true
  externalTimeoutMs: 5000

ignore:
  - "drafts/**"
